<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://example.com/staff" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://com.BookStore/staf">
    <types>
        <xsd:schema>
            <xsd:import targetNamespace="http://com.BookStore/staf" schemaLocation="staff.xsd"/>
        </xsd:schema>
    </types>
    <message name="AddRemoveStaffRequest">
        <part name="staff" element="tns:Staff"/>
    </message>
    <message name="AddRemoveStaffResponse">
        <part name="result" type="xsd:boolean"/>
    </message>
    <portType name="StaffPortType">
        <operation name="AddRemoveStaff">
            <input message="tns:AddRemoveStaffRequest"/>
            <output message="tns:AddRemoveStaffResponse"/>
        </operation>
    </portType>
    <binding name="StaffBinding" type="tns:StaffPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="AddRemoveStaff">
            <soap:operation soapAction="http://example.com/staff/AddRemoveStaff"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="StaffService">
        <port name="StaffPort" binding="tns:StaffBinding">
            <soap:address location="http://example.com/staff"/>
        </port>
    </service>
</definitions>
